### ISSUE TITLE
Showing position with 0 shares due to pending limit buy

### ISSUE THREAD

**Issue by cdtweb** [s0up/robinhood-electron#10]
![screen shot 2017-09-20 at 9 19 04 am](https://user-images.githubusercontent.com/4228665/30652134-d189639e-9de4-11e7-947e-d35133724e6d.png)

Notice the $XXII position.. I have a limit buy at $3.00 for 12 shares but it hasn't been submitted yet.

**Comment by s0up** [comment]
Does the mobile app have this same behavior? I'm using the API call for retrieving "non zero" positions, but I have also noticed the same thing you did.  Was not sure if it was a "feature" or a "bug"!

**Comment by cdtweb** [comment]
The mobile app does not show the position.

**Comment by s0up** [comment]
Fixed on master.  It'll be included in the next release build.

https://github.com/s0up/robinhood-electron/commit/9ffabb0fc996b0bfb43be2ac7fd7a48c4b6f7956
