### ISSUE TITLE
Add support for 2FA

### ISSUE THREAD

**Issue by jasperwalia** [s0up/robinhood-electron#7]
Client tells you 2FA code is needed, but no entry to actually enter the code

**Comment by s0up** [comment]
Alpha 0.7.2 is being uploaded right now.  I've gone ahead and added 2-step authentication support. Test it out and let me know if it works properly for you, and I'll close this issue 👍

**Comment by jasperwalia** [comment]
Works like a charm,thanks!

**Comment by s0up** [comment]
Perfect --
